---
- hosts: database
  become: true
  user: osboxes
  vars:
    packages:
      - name: firewalld
      - name: mariadb-server

    services:
      - name: firewalld
      - name: mariadb

  tasks:
    - name: Install "{{ item.name }}" on Database
      yum:
        name: "{{ item.name}}"
        state: present
      loop: "{{ packages}}"
    - name: Turn on "{{ item.name }}" on Database
      systemd:
        name: "{{ item.name }}"
        state: started
      loop: "{{ services }}"
    - name: Enable port on firewall
      firewalld:
        permanent: yes
        zone: public
        port: 3036/tcp
